### PR TITLE
Fix port redirection issues with Docker 0.7

### PR DESCRIPTION
**Pull request by BYK**
Docker 0.7 changed the default behavior for port redirections
which broke the whole project. This patch makes changes to
accomodate the new port forwarding logic and requirements.

### CODE REVIEW

**Comment by kynan** [comment]
I've just tried this on a clean Ubuntu 12.04 64-bit VM with Docker 0.7.1 and it failed with

```
KeyError: 4200
```

on [this line](https://github.com/BYK/jiffylab/blob/fix-ports/webapp/app.py#L168).

What might I have done wrong? I've installed jiffylab via the provided install script.

**Comment by BYK** [comment]
@kynan, my bad. I have struggled a lot with this issue and finally got it working and updated the protocol version too.

I'll update my branch soon.

**Comment by kynan** [comment]
@BYK thanks, looking forward to that!

**Comment by BYK** [comment]
@kynan took a while for me to update the PR, sorry :(

It's ready now. I also did some formatting, I can revert them if you want tho.

**Pull request closed without merging**
